# Generated by Django 3.1.1 on 2020-10-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='services_type',
            field=models.CharField(blank=True, choices=[('PLATINUM', 'Platinum'), ('GOLD', 'Gold')], max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
